# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170502_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('old_price', models.PositiveIntegerField()),
                ('new_price', models.PositiveIntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='discount/')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('old_price', models.PositiveIntegerField()),
                ('new_price', models.PositiveIntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='new_products/')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
    ]
