# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170502_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproduct',
            old_name='new_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='newproduct',
            name='old_price',
        ),
    ]
