# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170502_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='NewProduct',
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('discount', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('standard', 'standard'), ('discount', 'discount'), ('new_product', 'new_product')], default='standard', max_length=20),
        ),
    ]
