# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170502_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('standard', 'Standard'), ('discount', 'Discount'), ('new', 'New product'), ('day', 'Product of the day')], default='standard', max_length=20),
        ),
    ]
