# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20170503_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expire_date',
            field=models.DateTimeField(null=True),
        ),
    ]
