# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20170508_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategories',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Subcategory'),
        ),
    ]
