# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_subcategory_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='categories',
            new_name='category',
        ),
    ]
